export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_ERROR = 'ADD_MOVIE_ERROR';

export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';
export const EDIT_MOVIE_ERROR = 'EDIT_MOVIE_ERROR';

export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_ERROR = 'DELETE_MOVIE_ERROR';

export const IMPORT_MOVIES_SUCCESS = 'IMPORT_MOVIES_SUCCESS';
export const IMPORT_MOVIES_ERROR = 'IMPORT_MOVIES_ERROR';
